import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Creator Hub",
  description: "Terms of Service for Creator Hub — rules and guidelines for using our AI creator tools.",
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  const lastUpdated = "January 1, 2025";

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-stone-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-stone-400 mb-10">Last updated: {lastUpdated}</p>

        <div className="prose prose-stone max-w-none space-y-6 text-sm leading-relaxed text-stone-600">
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">1. Agreement to Terms</h2>
            <p>
              By accessing or using Creator Hub ("Service", "we", "us", "our"), you agree to be
              bound by these Terms of Service. If you disagree with any part of these terms, you
              may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">2. Description of Service</h2>
            <p>
              Creator Hub provides free, AI-powered tools for content creators, including:
            </p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Background Remover — AI-based image background removal</li>
              <li>Image Compressor — image file size optimization</li>
              <li>Caption Generator — AI-generated social media captions</li>
              <li>Hashtag Generator — AI-generated hashtag sets with scoring</li>
              <li>Video Title Generator — AI-generated video titles with CTR/SEO scoring</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">3. Usage Limits</h2>
            <p>
              To ensure fair access for all users and to manage operating costs, each tool is
              subject to a daily usage limit per IP address. We reserve the right to adjust these
              limits at any time without notice. Attempting to circumvent these limits (e.g., via
              VPNs, proxies, or automated scripts) may result in being blocked from the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">4. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Upload or generate content that is illegal, harmful, defamatory, or infringes on intellectual property rights</li>
              <li>Generate content that is hateful, harassing, sexually explicit, or violent</li>
              <li>Upload images of other people without their consent</li>
              <li>Attempt to reverse-engineer, scrape, or overload the Service</li>
              <li>Use automated tools (bots, scripts) to access the Service beyond normal human usage</li>
              <li>Violate any applicable local, state, national, or international law</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">5. AI-Generated Content Disclaimer</h2>
            <p>
              Captions, hashtags, and titles generated by our tools are produced by third-party
              AI models (Groq's LLaMA models) and are provided for inspiration and productivity
              purposes only. We do not guarantee the accuracy, originality, performance (CTR,
              SEO ranking, engagement), or suitability of any AI-generated content. Difficulty,
              popularity, CTR, and SEO scores are AI-generated estimates and should not be
              treated as guaranteed metrics. You are solely responsible for reviewing and
              verifying any content before publishing it.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">6. Uploaded Content Ownership</h2>
            <p>
              You retain all ownership rights to images you upload. By uploading an image, you
              grant us a temporary, limited license to process that image through our
              third-party providers (remove.bg, Cloudinary, Sharp) solely to deliver the
              requested result to you. We do not claim ownership of your uploaded or generated
              content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">7. Advertising</h2>
            <p>
              This Service is supported by advertising, including Google AdSense. By using the
              Service, you agree to the display of advertisements. We are not responsible for the
              content of third-party advertisements.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">8. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" and "as available" without warranties of any kind,
              either express or implied. We do not warrant that the Service will be
              uninterrupted, error-free, or free of harmful components.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Creator Hub shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages resulting from
              your use of, or inability to use, the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">10. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Continued use of the
              Service after changes constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-2">11. Contact Us</h2>
            <p>
              Questions about these Terms can be sent to{" "}
              <a href="mailto:faisalagentai@gmail.com" className="text-violet-600 underline">
                faisalagentai@gmail.com
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
